force-app/main/default/objects/Fire__c/Fire__c.object-meta.xml
<CustomObject>
    <label>Fire</label>
    <nameField>
        <label>Fire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fire__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Calculates age in days</description>
    <formula>IF( NOT( ISBLANK( Startdate__c ) ) ,
  IF( DATE( 2000 , MONTH( Startdate__c ) , DAY( Startdate__c ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
      DAY (Today()) - DAY ( IF( NOT( ISBLANK( Stopdate__c ) ), Stopdate__c ), Startdate__c ),
      DAY (Today()) - DAY ( IF( NOT( ISBLANK( Stopdate__c ) ), Stopdate__c ), Startdate__c ) -1 ),
  null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fire__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Radius__c</fullName>
    <label>Radius (cm)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fire__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity (%)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fire__c/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <label>Supervisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fires</relationshipLabel>
    <relationshipName>Fires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fire__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature (celcius)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FireController.cls
public with sharing class FireController {
    @AuraEnabled(Cacheable=true)
    public static Fire__c[] getAllFires() {
        return [
            SELECT
                Id,
                Name,
                Age__c,
                Radius__c,
                Temperature__c,
                Humidity__c,
                Height__c,
                Weight__c,
                Location__Latitude__s,
                Location__Longitude__s,
                Supervisor__r.Name
            FROM Fire__c
            ORDER BY Name
            LIMIT 50
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static Fire__c[] searchFires(String searchTerm) {
        // Return all Fires when no search term
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllFires();
        }
        // Prepare query paramters
        searchTerm = '%' + searchTerm + '%';
        // Execute search query
        return [
            SELECT
                Id,
                Name,
                Age__c,
                Radius__c,
                Temperature__c,
                Humidity__c,
                Height__c,
                Weight__c,
                Location__Latitude__s,
                Location__Longitude__s,
                Supervisor__r.Name
            FROM Fire__c
            WHERE Name LIKE :searchTerm
            ORDER BY Name
            LIMIT 50
        ];
    }
}